### ISSUE TITLE
caravel submodule link missing

### ISSUE THREAD

**Issue by vijayank88** [hhj1107/junga_soc_mpw4#1]
Hi,
Can you update caravel submodule link, its seems broken as missing .gitmodules

Thanks..

**Comment by hhj1107** [comment]
The caravel folder should be populated by running:
```
make install
```
The file .gitmodules has been removed from the original repo this is ultimately cloned from:
https://github.com/efabless/caravel_user_project/commit/abdc9e92db0001a474aede8ff1d2d27a9407c44f#diff-fe7afb5c9c916e521401d3fcfb4277d5071798c3baf83baf11d6071742823584
If you insist, we can add .gitmodule back but it will break `make install` command.

**Comment by hhj1107** [comment]
We have added caravel folder: https://github.com/hhj1107/junga_soc_mpw4/commit/396a2e6b2ad737323f6533f87298a1ad1eee3b46
